#!/usr/bin/env python

# A PYTHON EXECUTABLE THAT LETS ME EASILY CREATE A JAVASCRIPT COMMENT HEADING FOR MY SCRIPTS
# /**
# * ----------------------------------------
# * THIS IS A SAMPLE HEADING FOR MY SCRIPT!
# * ----------------------------------------
# *
# */

def create_heading():
    heading = input("Type JS heading:\n")
    len_heading = len(heading)
    line = "* -"
    while len_heading >= 1:
        line = line + "-" 
        len_heading-=1
    print("\n\n")
    print("/**")
    print(line)
    print("*", heading.upper())
    print(line)
    print("*\n*/")
    print("\n\n")
create_heading()

